apiVersion: v2
name: device-managment
description: A Helm chart for device managment app
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: "15.5.20"
    repository: oci://registry-1.docker.io/bitnamicharts