@startuml
!include <c4/C4_Container.puml>

title Smart home system

Person_Ext(customer, User, "")
System_Ext(api_access, "External Device", "")

System_Boundary(sms, "Smart home system") {
    Container(frontend, "Web UI", react)
    Container(api_gateway, "(Api Gateway/LB)", Nginx)
    Container(message_broker, "Message broker", Kafka)
    Container(device_management_service, "Device Management Service", C#, "")
    Container(telemetry_service, "Telemetry Service", C#, "")
    Container(scenario_service, "Scenario Service", C#, "")
    Container(home_admin_service, "Home Administration Service", C#, "")
    ContainerDb(db_home_admin, "Home Administration Service Storage", "PostgreSQL", "")
    ContainerDb(db_scenario, "Scenario Service Storage", "PostgreSQL", "")
    ContainerDb(db_dms, "Device Management Service Storage", "PostgreSQL", "")
    ContainerDb(db_telemetry, "Telemetry Storage", "PostgreSQL", "")
}

Rel(customer, frontend, "Uses", "JSON/https")
Rel(frontend, api_gateway, "Uses", "JSON/https")

Rel(api_gateway, message_broker, "Uses", "")

Rel(message_broker, device_management_service, "JSON/https")
Rel(message_broker, telemetry_service, "JSON/https")
Rel(message_broker, scenario_service, "JSON/https")
Rel(message_broker, home_admin_service, "JSON/https")


Rel(home_admin_service, db_home_admin, "Read/Write")

Rel(device_management_service, db_dms, "Read/Write")
Rel(telemetry_service, db_telemetry, "Read/Write")
Rel(scenario_service, db_scenario, "Read/Write")

Rel(device_management_service, api_access, "Uses", "JSON/https")
Rel(telemetry_service, api_access, "Uses", "JSON/https")
@enduml